export const GET_ANIME_START = 'GET_ANIME_START';
export const GET_ANIME_SUCESS = 'GET_ANIME_SUCESS';
export const GET_ANIME_FAIL = 'GET_ANIME_FAIL';
export const GET_ANIME_DETAILS_START = 'GET_ANIME_DETAILS_START';
export const GET_ANIME_DETAILS_SUCESS = 'GET_ANIME_DETAILS_SUCESS';
export const GET_ANIME_DETAILS_FAIL = 'GET_ANIME_DETAILS_FAIL';
